export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_LOCAL_SUCCESS = 'FETCH_LOCAL_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const FEEDBACK_TEL = 'FEEDBACK_TEL';

export const CLEAN_CART = 'CLEAN_CART';

export const CONSTRUCTOR_NEXT = 'CONSTRUCTOR_NEXT';
export const CONSTRUCTOR_PREV = 'CONSTRUCTOR_PREV';

export const INGREDIENT_ADD = 'INGREDIENT_ADD';
export const INGREDIENT_REMOVE = 'INGREDIENT_REMOVE';